Task1
danielsheh02/high-performance-graph-analysis-course pull request #1
Opened 2023-03-13 19:45 UTC by danielsheh02

## Подготовка
- [ ] Сделать публичный `fork` данного репозитория.
- [ ] Добавить ссылку на ваш `fork` в [таблицу](https://docs.google.com/spreadsheets/d/1VAfnSGd63GulSdig8TLISOXBF7MMIUm3egO4U_jdugI/edit?usp=sharing).
- [ ] Добавить в совладельцы форка одного из ассистентов (чтобы узнать, кого именно, нужно посмотреть в [таблицу](https://docs.google.com/spreadsheets/d/1VAfnSGd63GulSdig8TLISOXBF7MMIUm3egO4U_jdugI/edit?usp=sharing))

## Задача

Везде считаем, что вершины графа занумерованы подряд с нуля.

- [ ] Используя pygraphblas реализовать функцию обхода ориентированного графа в ширину из заданной вершины. При этом организовать все вычисления в виде операций над векторами и матрицами.
  - [ ] Функция принимает представление графа, удобное для неё (загрузка, конвертация реализованы отдельно) и номер стартовой вершины.
  - [ ] Функция возвращает массив, где для каждой вершины указано, на каком шаге она достижима. Стартовая вершина достижима на нулевом шаге, если вершина не достижима, то значение соответствующей ячейки равно -1.
- [ ] Добавить необходимые тесты.
- [ ] Добавить запуск тестов с помощью `pytest` в `.github/workflows/`.
    - Проверить, что тесты запускаются только на linux.

2023-03-14 10:40 UTC, rustam-azimov requested changes

2023-03-14 10:40 UTC, rustam-azimov commented on project/bfs.py
> +    while old_steps_nvals != steps.nvals:
пока front не пуст

2023-03-14 10:40 UTC, rustam-azimov commented on project/bfs.py
> +        front.vxm(graph, out=front)
умножение сразу с маской комплементарной по steps

2023-03-14 10:40 UTC, rustam-azimov commented on project/bfs.py
> +        current_visited_mask = front.eadd(steps.S, add_op=BOOL.GT, mask=front.S)
curent_visited тогда не нужен

2023-03-14 10:40 UTC, rustam-azimov commented on tests/test_bfs.py
> +        (
Лучше сразу реализовать функцию считывания графа с файла, преобразование в nx graph и матрицу графбласа

2023-03-16 06:47 UTC, danielsheh02 commented on tests/test_bfs.py
> +        (
В каком виде лучше представлять графы? В dot, свое представление придумать или достаточно просто матрицы смежности?

2023-03-18 07:49 UTC, rustam-azimov commented on tests/test_bfs.py
> +        (
В принципе, в каком удобно Вам для написания тестов. В файле моожно COO формат.

2023-03-20 07:17 UTC, rustam-azimov approved these changes

2023-03-20 15:46 UTC, merged